services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      XDEBUG_MODE: coverage
    tty: true
